### ISSUE TITLE
Decouple SoftDevice and self uf2

### ISSUE THREAD

**Issue by hathach** [adafruit/Adafruit_nRF52_Bootloader#126]
**Is your feature request related to a problem? Please describe.**
Decouple softdevice along with adding self uf2. There is a duplicate issue of some sort, but I create this new one anyway.

**Describe the solution you'd like**
UF2 can be used to upgrade 
- Bootloader  (family ID = 0xd663823c) , with check for BOOTLOADER ID in cf2
- Application and/or SoftDevice (family ID = 0xADA52840)

For UF2 Softdevice can be bundled together <s>with either bootloader or</s> application into a single UF2 file. 

CDC interface will left as it is as fail-safe since CDC can be used to revert to good-old version, should something bad happens.

Note: MBR is required to work with and without Softdevice (dynamically). MBR ROM & RAM requirement is as follows:
- Flash 0x0000 - 0x1000 (first page) 
- RAM 0x20000000-0x20000008 ( first 8 bytes).

**Check list**
- [x] uf2 works with or without a SD on the flash
- [x] uf2 works with application only
- [x] uf2 works with softdevice only
- [x] uf2 works with application + softdevice
- [x] uf2 works with bootloader only
- [x] uf2 only update bootloader of the same board (using BOARD ID in cf2 config)
- [x] uf2 work with CURRENT.UF2 read from device
- <s>[ ] uf2 works with bootloader + softdevice</s>
- [x] cdc works with application as it does now
- [x] cdc works with bootloader + softdevice as it does now
- [ ] ota should work when SD is on the flash: not tested, but should not change. This is subject to change in the next bootloader update

@dhalbert for review/discuss

**Comment by orrmany** [comment]
Hi @hathach , I am not sure if I understand the USB lingo, I am sorry.  
Basically this is my use case:

Suppose that I, as an Adafruit customer, previously purchased an Adafruit MCU with an nRF52 SoC onboard. 

Now, also suppose that I, as an Arduino developer, would like to be able replace the stock SoftDevice (SD) delivered with product with itd to a multiprotocol alternative, i fit exist. 
- For example, I would like to have the S140 SD of the nRF52840 Feather Express  replaced with S340. 
- Another example would be a nRF52832 customer who would like to replace S132 with S332. 
- etc.

I would like to retain all legacy Adafruit functionality with the alternative, multiprotocol SoftDevices, since the functionality of the alternative SD-s are extensions of that of the their lesser, BLE only counterparts. That is, I would like to use CircuitPython, DFU, Bluefruit, etc. with the multiprotocol SD-s.

Could you explain what of those checklist items of yours are applicable to my use case?

Thanks, Gábor

**Comment by orrmany** [comment]
Oh, and I would like to retain the DFU capability over serial. For example, today I am using nRF52840 with a computer, where USB Mass Storage is blocked for administrative reasons. That is, UF2 (whatever UF2 means) is not an option for me.

**Comment by hathach** [comment]
@orrmany please don't hijack this issue which is about decoupling Softdevice, you could ask S340 related issue on your own issue/pr.

**Comment by orrmany** [comment]
Oh, I thought that checklist a questionnaire. Deleting comment here then

**Comment by orrmany** [comment]
@hathach : how do you plan to handle the differences among the RAM allocation needs with/without softdevice? And the RAM allocations differences between alternative softdevices?

**Comment by hathach** [comment]
> @hathach : how do you plan to handle the differences among the RAM allocation needs with/without softdevice? And the RAM allocations differences between alternative softdevices?

It is application specific and have nothing to do with the bootloader.

**Comment by hathach** [comment]
implemented by #128
