### ISSUE TITLE
USB Mass Storage with UF2 Support

### ISSUE THREAD

**Issue by microbuilder** [adafruit/Adafruit_nRF52_Bootloader#4]
A secondary bootloader interface should be mass storage with [UF2](https://github.com/Microsoft/uf2) file format support, which is used on certain CirtcuitPython targets for drag and drop updates and 'execute on save' file support.

The mass storage device should point to the internal file system.

For details on an existing UF2 bootloader see: https://learn.adafruit.com/adafruit-feather-m0-express-designed-for-circuit-python-circuitpython/uf2-bootloader-details

**Comment by hathach** [comment]
- [ ] disk volume (11 chars limit) : "nrf52840uf2" 
- [ ] can upgrade application
- [ ] prohibit upgrading Softdevice and/or bootloader
- [ ] Won't expose file system on flash, only accept uf2 file, to prevent user confusion

**Comment by ladyada** [comment]
@mmoskal hey now that DK's are available - want to come along on this journey and help advise? 
@hathach mmoskal wrote the original UF2 bootloader and may be able to help if you have questions!

**Comment by hathach** [comment]
ah thanks a lot, I got the MSC UF2 up and running (currently read only) and using @mmoskal  ghostfast.c from https://github.com/Microsoft/uf2-nrf5 . However there is a couple of issue with nrf52 usb driver with large enough data (reading current.uf2 file). Once this usb driver is addressed, we should have a full working uf2 port

![image](https://user-images.githubusercontent.com/249515/41805486-8cbb9b04-76d5-11e8-9b70-f95ca55e99f3.png)

**Comment by hathach** [comment]
the uf2 implementation is ready to test. 
@mmoskal  we modify your ghostfat.c a bit
https://github.com/adafruit/Adafruit_nRF52840_Bootloader/blob/master/src/usb/uf2/ghostfat.c

Since we didn't use the secure bootloader come with sdk14. Also it only allows to update the application only, forbid the bootloader and/or Softdevice upgrade with uf2. The reason is it is pretty easy to brick the device with another uf2 from other chip such as sam51 by mistake (drag and drop).

**Comment by ladyada** [comment]
oh that is a very good point. mmoskal, do we have a way of identifying the target chip or a special magic number to identify that this is for a specific chip in UF2?

**Comment by mmoskal** [comment]
Right, I thought about it several times but always got distracted with something else.

Here's a proposal: https://github.com/Microsoft/uf2/pull/6

Let me know what you think!

**Comment by mmoskal** [comment]
Also, I think you should always prevent re-flashing of the bootloader itself. To re-flash the bootloader we would need to flash a user-space program that re-writes the bootloader, like in SAMD21.

You could (and I guess should) allow direct re-flashing MBR and SD provided the bootloader doesn't need them to function.

**Comment by hathach** [comment]
For SD, it still got a risk though, major version e.g  5 and 6 got a complete different of API and parameters for advertising even stack enabling function, hence different SVC number for those calls. The bootloader may not work with the later SD and could cause a brick e.g when doing OTA since we support that as well. And currently we did enable the SD while doing uf2 writing.

Maybe I am playing too safe here, however, we also has USB CDC which can take care of upgrading bootloader + SD combo (tested altogether), user drag and drop is quite a prone of errors. @ladyada what do you think, I would change it you feel it is necessary.

**Comment by ladyada** [comment]
yes this is quite a challenge! 
i have a question: i know softdevices is needed for BTLE and some chip functions. 

what part of the USB interface interacts with softdevice? is there any to separate CDC/MSD USB stack from softdevice so we don't initialize it in the bootloader?

**Comment by mmoskal** [comment]
You shouldn't need SD for USB.

I think we could treat bootloader and SD as "firmware" and update it at the same time using the embed-in-user-app trick (which doesn't require anything from the bootloader). Then we would not include SD in UF2 files generated from MakeCode. Of course we could still run into problems when the firmware is older than user app requires but arguably user app has more ways of communicating that to the user

**Comment by ladyada** [comment]
mm, USB may not but if we wanted to do webbluetooth programming, and i assume we do long term, the OTA bootloader does for sure.

**Comment by mmoskal** [comment]
I think it would be wise to have the SD we ship with bootloader leave a bit more space than Nordic says, so that future upgrades are less likely to break stuff. I guess they should stabilize the SVC numbers in SD at some point...

**Comment by hathach** [comment]
@mmoskal agreed, our current bootloader code is 32 KB and 4KB of setting page. I even saw tannewt complain why the size is that big :)) . yeah, since it will allow us to go with secure bootloader and dfu on serial + usb + ble if needed. The bootloader size is hard coded into ucir which require an chip erase to change, I think we can't change that within code. the chip has 1MB, plenty to spare :).

@ladyada got it, we could add it later if needed. Bootloader + SD is still upgradable via good old cdc interface.

**Comment by ladyada** [comment]
ok that sounds very good
mmoskal, if you can help test the bootloader on the codal/mbed side, that would be really appreciated :)

**Comment by mmoskal** [comment]
Well, there's size of bootloader (which is at the end of flash) and SD (which is at the beginning). I was saying to allocate a bit more space for SD (I'm not 100% sure SD supports this out of the box).

I believe you can clear UICR separately from the rest of the chip with `ERASEUICR`

As for the "secure" part I would be inclined to just remove it - it has very little usefulness on maker boards (it's for the manufacturer to lock the firmware to whatever they release).

**Comment by hathach** [comment]
@mmoskal  Ah sorry, I interpret your post due to sleepiness ( I live on the other side of the earth :D ). You are right on the erasing uicr :) thanks for the update. 
I agree, if you intend to update the SD, it is better to just give it more space e.g 0x30000 since the chip has plenty left. The "secure" dfu is like you said for locking bootloader, we debate for some time and decide to go with the good old dfu as current.

@ladyada  I will try to rewrite the bootloader a bit to only enable SD when doing OTA. This will has least modification to mmoskal's uf2 port for nrf52 which will benefit others as well.

**Comment by ladyada** [comment]
ok for enable SD with OTA only, please put in a github issue to remind yourself for later. 

the most important for me is to get UF2 working (sounds like it is :) and then add USB CDC and MSD to circuitpython so we start doing testing! we got more nrf52840 modules yesterday so i think they will be available soon!
